@startuml

title __EXCEPTIONS's Class Diagram__\n

    namespace uce.proyect {
      namespace exceptions {
        class uce.proyect.exceptions.CarnetException {
            - estimacionfechaSegundaDosis : LocalDate
            - fechaPrimeraDosis : LocalDate
            - tipoVacuna : String
            + CarnetException()
            + CarnetException()
            + equals()
            + getEstimacionfechaSegundaDosis()
            + getFechaPrimeraDosis()
            + getTipoVacuna()
            + hashCode()
            + setEstimacionfechaSegundaDosis()
            + setFechaPrimeraDosis()
            + setTipoVacuna()
            + toString()
            # canEqual()
        }
    }
  }
  

    namespace uce.proyect {
      namespace exceptions {
        class uce.proyect.exceptions.NoEncontradorException {
            + NoEncontradorException()
        }
    }
  }
  

    namespace uce.proyect {
      namespace exceptions {
        class uce.proyect.exceptions.PlanException {
            - fase : String
            - fechaFinal : LocalDate
            - fechaInicio : LocalDate
            - personasVacunadas : Integer
            + PlanException()
            + PlanException()
            + equals()
            + getFase()
            + getFechaFinal()
            + getFechaInicio()
            + getPersonasVacunadas()
            + hashCode()
            + setFase()
            + setFechaFinal()
            + setFechaInicio()
            + setPersonasVacunadas()
            + toString()
            # canEqual()
        }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
