@startuml

title __REPOSITORIES's Class Diagram__\n

    namespace uce.proyect {
      namespace repositories {
        interface uce.proyect.repositories.AdministradorRepository {
            {abstract} + findByUsuario()
        }
    }
  }
  

    namespace uce.proyect {
      namespace repositories {
        interface uce.proyect.repositories.CarnetRepository {
            {abstract} + findByEstudiante()
            {abstract} + findByEstudianteAndInoculacionVoluntaria()
            {abstract} + findByEstudianteAndInoculacionVoluntariaAndPrimeraDosis()
      }
    }
  }
  

    namespace uce.proyect {
      namespace repositories {
        interface uce.proyect.repositories.EstudianteRepository {
            {abstract} + findByCarrera()
            {abstract} + findByUsuario()
      }
    }
  }
  

    namespace uce.proyect {
      namespace repositories {
        interface uce.proyect.repositories.FacultadRepository {
            {abstract} + findByCarreras()
            {abstract} + findByNombre()
        }
    }
  }
  

    namespace uce.proyect {
      namespace repositories {
        interface uce.proyect.repositories.PlanRepository {
            {abstract} + findByCompleto()
            {abstract} + findByFacultad()
            {abstract} + findByFacultadAndFase()
            {abstract} + findByFaseAndCompletoAndFechaInicioLessThanEqual()
            {abstract} + findByFechaInicio()
            {abstract} + findByFechaInicioAndFase()
      }
    }
  }
  

    namespace uce.proyect {
      namespace repositories {
        interface uce.proyect.repositories.UserRepository {
            {abstract} + findByNombreUsuario()
        }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
