@startuml

title __AGREEMENT's Class Diagram__\n

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.AdministradorService {
            {abstract} + agregar()
      }
    }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.CarnetService {
            {abstract} + actualizarCarnetVacunado()
            {abstract} + buscarCarnetPorEstudiante()
            {abstract} + generarPdfEnBytes()
        }
    }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.CoreService {
            {abstract} + agregarOActualizar()
            {abstract} + buscarPorId()
            {abstract} + eliminar()
            {abstract} + listar()
        }
      }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.EmailService {
            {abstract} + enviarComprobante()
            {abstract} + enviarEmail()
            {abstract} + enviarEmailCredenciales()
            {abstract} + enviarEmailPlan()
      }
    }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.EstudianteService {
            {abstract} + agregar()
            {abstract} + buscarEstudiantesPorFacultadYCarrera()
            {abstract} + buscarEstudiantesPorFacultadYCarreraYSemestre()
            {abstract} + nombres()
      }
    }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.FacultadService {
            {abstract} + agregarCarrera()
      }
    }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.PlanService {
            {abstract} + buscarPorFecha()
            {abstract} + establecerPlanes()
            {abstract} + generarNotificacionVacuncacion()
            {abstract} + obtenerEstudiantesAInocular()
            {abstract} + porcentajeInoculados()
      }
    }
  }
  

    namespace uce.proyect {
      namespace service.agreement {
        interface uce.proyect.service.agreement.UserService {
        }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
